### ISSUE TITLE
change rofi dependency to rofi-wayland

### ISSUE THREAD

**Issue by Ezorp** [PilkDrinker/PilkDots#11]
The package provided as the dependency, and installed by the script (the one for Arch Linux in my case) is the standard rofi which doesn't support the animations of the dotfiles, simply using the rofi-wayland package fixed the issue. (the keybind don't need to be changed)

**Comment by PilkDrinker** [comment]
I totally forgot about that I changed to rofi-wayland. Thanks for reminding me! Fixing this now.
