### ISSUE TITLE
Problem in hyprland mappings

### ISSUE THREAD

**Issue by DBSuwu** [PilkDrinker/PilkDots#7]
After I installed a clean Arch Linux (on VMware) it started to appear a bit strange, I did everything one by one and this is what happened.
All that opens is explorer and wallpaper, the rest crumbles and won't open
https://youtu.be/H9ANFFZLtis Here is a video of how I installed (I think I screwed up somewhere or forgot to write) 
![image](https://github.com/user-attachments/assets/b122b7b7-4bfe-41b1-bbf0-e77a10b18e5a)

**Comment by DBSuwu** [comment]
![image](https://github.com/user-attachments/assets/0cea935a-a585-4800-b4fe-2f5bfce0c3b5)
![image](https://github.com/user-attachments/assets/f31d9566-278b-444b-9e11-5d53e014e6d3)
that's what I highlighted to the system

**Comment by Githubguy132010** [comment]
The script is still beiing worked on. Expect some issues.

**Comment by PilkDrinker** [comment]
Seems that's its missing the [fonts](https://github.com/PilkDrinker/PilkDots/blob/master/Required%20Fonts) try installing them. As per the mapping I have no idea. Can you show a screenshot of the keybindings of ~/.config/hypr/hyprland.conf?

**Comment by DBSuwu** [comment]
![Other Linux 5 x kernel 64-bit-2024-11-10-16-16-08](https://github.com/user-attachments/assets/8d481cdb-0917-4083-a025-c35f47e3b0b1)
![Other Linux 5 x kernel 64-bit-2024-11-10-16-16-15](https://github.com/user-attachments/assets/91a5d1b6-e07f-4302-a667-fa30662bbc79)

**Comment by PilkDrinker** [comment]
Well there doesn't seem to be any issues there. 

This might be a stupid question, but what keyboard layout do you use? - I set the default layout to US in the hyprland.conf file.

**Comment by DBSuwu** [comment]
![image](https://github.com/user-attachments/assets/763533c5-579c-4057-bd36-94caa943951e)
When I installed, I installed them. Could this be the problem?

**Comment by DBSuwu** [comment]
The only reason is VMware, I have no other ideas

**Comment by PilkDrinker** [comment]
I have tried the install script myself and did not encounter any problems besides some missing fonts. I've never used VMware myself, so it might just be a VMware issue. 

hyprland has been a bit iffy in VMs in my own experience. So I would suggest trying it on a normal machine without archinstall.
